dataset: mot

train_split: mot17_train_cross_val_frame_0_0_to_0_5_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

mot_path_train: data/MOT17
mot_path_val: data/MOT17

sequence_frames: 17

# Training
epochs: 50
lr_drop: 10

# Evaluation
max_num_of_frames_lookback: 4